<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Routing\UrlGenerator;
use Carbon\Carbon;
use App\Mail\CampRegistration;
use \Illuminate\Support\Facades\URL;

class CampRegistrationController extends Controller
{
    protected $places;

    public function registration(){
        $places = \App\place::all();
        return view('Pages/registration', ['places' => $places]);
    }

    public function registrationLeader(){
        $places = \App\place::all();
        return view('Pages/registration-leader', ['places' => $places]);
    }
    
    public function registrationDone(){
        return view('Pages/registrationdone');
    }

    // Standard attendee
    public function store(){

        // Redirects and will not register if all spots are full
        if(!SpotFree()){
            return redirect('/registrationfull');
        }

        $registration= new \App\Registration();
        //return request()->all();
        
        $registration->first_name = Request('firstName');
        $registration->last_name = Request('lastName');
        $registration->birthdate = Request('birthdate');
        $registration->last_four = Request('fourLast');
        $registration->address = Request('address');
        $registration->zip = Request('zip');
        $registration->city = Request('city');
        $registration->email = Request('email');
        $registration->phonenumber = Request('phoneNumber');
        $registration->allergy = Request('allergy');
        $registration->first_name_advocate = Request('firstNameAdvocate');
        $registration->last_name_advocate = Request('lastNameAdvocate');
        $registration->email_advocate = Request('emailAdvocate');
        $registration->phone_number_advocate = Request('phoneNumberAdvocate');
        $registration->home_number = Request('homeNumberAdvocate');
        $registration->place = Request('place');
        $registration->member_place = Request('memberPlace');
        $registration->other = Request('other');
        $registration->terms = Request('terms');

        if(Request('memberPlace')==0){
            $registration->member = 0;
            $registration->member_place =null;
        }

        else{
            $registration->member = 1;
        }

        
        //$registration->verification_key = Hash::make($registration->first_name . $registration->phonenumber);
        $registration->save();

        // Verification link generated by registration id and verification key
        $verificationLink = Url::signedRoute('event.verifyRegistration', [
            'type' => 'participant', 
            'id' => $registration->id
            ]);
        
        // Send Email
        \Mail::to($registration->email_advocate)->send(new CampRegistration($registration, $verificationLink));

        return redirect('/registration/done');
    }

    // leader attendee
    public function storeLeader(){

        // Redirects and will not register if all spots are full
        if(!SpotFree()){
            return redirect('/registrationfull');
        }
        
        $registration= new \App\Registrations_leader();
        //return request()->all();
        
        $registration->first_name = Request('firstName');
        $registration->last_name = Request('lastName');
        $registration->birthdate = Request('birthdate');
        $registration->last_four = Request('fourLast');
        $registration->address = Request('address');
        $registration->zip = Request('zip');
        $registration->city = Request('city');
        $registration->email = Request('email');
        $registration->phonenumber = Request('phoneNumber');
        $registration->allergy = Request('allergy');
        $registration->first_name_advocate = Request('firstNameAdvocate');
        $registration->last_name_advocate = Request('lastNameAdvocate');
        $registration->email_advocate = Request('emailAdvocate');
        $registration->phone_number_advocate = Request('phoneNumberAdvocate');
        $registration->home_number = Request('homeNumberAdvocate');
        $registration->place = Request('place');
        $registration->member_place = Request('memberPlace');
        $registration->other = Request('other');
        $registration->terms = Request('terms');
        $registration->kitchen = Request('kitchen');

        if(Request('kitchen') > 0){
            $registration->cost = 1000;
        }
        else{
            $registration->cost = 1500;
        }

        if(Request('memberPlace')==0){
            $registration->member = 0;
            $registration->member_place =null;
        }

        else{
            $registration->member = 1;
        }

        
        //$registration->verification_key = Hash::make($registration->first_name . $registration->phonenumber);
        $registration->save();

        // Verification link generated by registration id and verification key
        $verificationLink = Url::signedRoute('event.verifyRegistration', [
            'type' => 'leader', 
            'id' => $registration->id
            ]);
        
        // Send Email
        \Mail::to($registration->email)->send(new CampRegistration($registration, $verificationLink));

        return redirect('/registration/done');
    }

    public function VerifyRegistration($type, $id){
        if($type == 'participant'){
            $fetchedRegistration = \App\registration::find($id);
            if($fetchedRegistration != null){
                $fetchedRegistration->verified_at = Carbon::now()->toDateTimeString();
                $fetchedRegistration->save();
            }
            return redirect('/registration/done');
        }
        elseif($type == 'leader'){
            $fetchedRegistration = \App\registrations_leader::find($id);
            if($fetchedRegistration != null){
                $fetchedRegistration->verified_at = Carbon::now()->toDateTimeString();
                $fetchedRegistration->save();
            }
        }
        else{
            return 'Något gick fel. Kontakta lägerledningen eller webansvariga';
        }
    }

    private function SpotFree(){
        $count = Registrations_leader::count() + Registration::count();
        if($count < 281) {
            return true;
        }
        else {
            return false;
        }
    }
}
