<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use Illuminate\Routing\UrlGenerator;
use Carbon\Carbon;
use App\Mail\CampRegistration;

class CampRegistrationController extends Controller
{
    protected $places;

    public function registration(){
        $places = \App\place::all();
        return view('Pages/registration', ['places' => $places]);
    }
    
    public function registrationDone(){
        return view('Pages/registrationdone');
    }

    public function store(){
        
        $registration= new \App\Registration();
        //return request()->all();
        
        $registration->first_name = Request('firstName');
        $registration->last_name = Request('lastName');
        $registration->birthdate = Request('birthdate');
        $registration->last_four = Request('fourLast');
        $registration->address = Request('address');
        $registration->zip = Request('zip');
        $registration->city = Request('city');
        $registration->email = Request('email');
        $registration->phonenumber = Request('phoneNumber');
        $registration->allergy = Request('allergy');
        $registration->first_name_advocate = Request('firstNameAdvocate');
        $registration->last_name_advocate = Request('lastNameAdvocate');
        $registration->email_advocate = Request('emailAdvocate');
        $registration->phone_number_advocate = Request('phoneNumberAdvocate');
        $registration->home_number = Request('homeNumberAdvocate');
        $registration->place = Request('place');
        $registration->member = 0; //Request('member');
        $registration->member_place = 0; //Request('memberPlace');
        $registration->other = Request('other');
        $registration->terms = 1; //Request('terms');
        
        $registration->verification_key = Hash::make($registration->first_name . $registration->phonenumber);

        $registration->save();

        // Verification link generated by registration id and verification key
        $verificationLink = url('/') . '/registration/verify/participant/' .$registration->id . '/' .$registration->verification_key;

        // Send Email
        \Mail::to($registration->email)->send(new CampRegistration($registration, $verificationLink));

        return redirect('/registration/done');
    }

    public function VerifyRegistration($type, $id, $key){
        if($type == 'participant'){
            $fetchedRegistration = \App\registration::find($id);
            if($fetchedRegistration->verification_key == $key){
                $fetchedRegistration->verified_at = Carbon::now()->toDateTimeString();
            }
            return view('Pages/gdpr');
        }
        elseif($type == 'leader'){
            $fetchedRegistration = \App\registrations_leader::find($id);
            if($fetchedRegistration->verification_key == $key){
                $fetchedRegistration->verified_at = Carbon::now()->toDateTimeString();
            }
        }
        else{
            return redirect('/');
        }
    }
}
